import { discoverFromSitemap } from './sitemap.mjs';
const uniq=a=>[...new Set((Array.isArray(a)?a:[]).map(String).filter(Boolean))];
const slug=s=>String(s||'item').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const type=s=>String(s||'component').replace(/^registry:/,'').replace(/^ui:/,'')||'component';
function licenseObj(v){if(!v)return null;return typeof v==='string'?{id:v}:v;}
export function normalizeShadcnPayload(payload,source){
  const raw=Array.isArray(payload)?payload:Array.isArray(payload?.items)?payload.items:(payload?.name?[payload]:null); if(!raw) throw Object.assign(new Error('invalid shadcn registry payload'),{code:'invalid_payload'});
  const seen=new Set(); return raw.map((item,i)=>{const name=slug(item.name||item.title||`item-${i+1}`);if(seen.has(name))throw Object.assign(new Error(`duplicate registry item: ${name}`),{code:'invalid_payload'});seen.add(name);const canCode=Boolean(source.allowCodeIngest&&source.policy?.codeIngestAllowed);const files=(item.files||[]).map(f=>({path:f.path||f.target||f.name||'',target:f.target||null,type:f.type||null,url:f.url||null,...(canCode&&typeof f.content==='string'?{content:f.content}:{})})).filter(f=>f.path);const prefix=source.installPrefix??(source.namespace?`@${source.namespace}/`:'');
    return {id:`${source.id}/${name}`,name,title:String(item.title||item.name||name),description:String(item.description||''),type:type(item.type),source:{id:source.id,name:source.name||source.id,url:source.url},tags:uniq([...(source.tags||[]),...(item.tags||[])]),categories:uniq(item.categories),frameworks:uniq(item.frameworks||['react']),dependencies:uniq(item.dependencies),devDependencies:uniq(item.devDependencies),registryDependencies:uniq(item.registryDependencies),files,docs:item.docs||null,envVars:item.envVars||null,cssVars:item.cssVars||null,css:item.css||null,font:item.font||null,meta:item.meta||null,license:licenseObj(item.license||source.license),install:{mode:'shadcn',address:item.installAddress||`${prefix}${name}`||null,requiresAuth:Boolean(source.requiresAuth)},design:{referenceUrl:item.url||item.docs||null,tokens:null,designMd:null,theme:null},performance:{clientRequired:item.clientRequired??null,runtime:uniq(item.runtime),estimatedCost:item.estimatedCost||null},retrieval:{local:true,remoteGet:false,remoteInstall:false,syncedAt:new Date().toISOString()}};});
}
async function collect(url,source,context,seenUrls=new Set(),names=new Set()){
  if(seenUrls.has(url)) throw Object.assign(new Error(`shadcn include cycle: ${url}`),{code:'invalid_payload'}); seenUrls.add(url);
  const {data}=await context.fetchJson(url); let items=normalizeShadcnPayload(data,source); for(const i of items){if(names.has(i.name))throw Object.assign(new Error(`duplicate registry item: ${i.name}`),{code:'invalid_payload'});names.add(i.name);}
  const includes=Array.isArray(data?.include)?data.include:Array.isArray(data?.includes)?data.includes:[];
  for(const inc of includes){const target=new URL(typeof inc==='string'?inc:inc.path||inc.url,url).toString();items=items.concat(await collect(target,source,context,new Set(seenUrls),names));}
  return items;
}
export const shadcnAdapter={id:'shadcn',async probe(source){return {ok:true,score:source.adapter==='shadcn'?100:5,capabilities:['sync','install']};},async sync(source,context){if(source.catalogItems)return normalizeShadcnPayload({items:source.catalogItems},source);if(source.sitemapUrl){const {text}=await context.fetchText(source.sitemapUrl,{sourceId:source.id});const discovered=discoverFromSitemap(text,source,{includePaths:source.sitemapInclude||[]});return normalizeShadcnPayload({items:discovered},source);}const url=source.manifestUrl||source.catalogUrl||source.url;return collect(url,source,context);}};
