export const DEFAULT_SOURCES = [
  ['shadcn','shadcn/ui','https://ui.shadcn.com','components design-system react tailwind'],
  ['21st','21st.dev','https://21st.dev','components registry react ai'],
  ['magicui','Magic UI','https://magicui.design','components animation react marketing'],
  ['aceternity','Aceternity UI','https://ui.aceternity.com/components','components animation react tailwind'],
  ['open-props','Open Props','https://open-props.style','css tokens design-system'],
  ['obsidianui','Obsidian UI','https://www.obsidianui.dev/components','components react'],
  ['rewampui','Rewamp UI','https://www.rewampui.com/components','components react'],
  ['watermelon','Watermelon UI','http://ui.watermelon.sh','components blocks shadcn'],
  ['motion-primitives','Motion Primitives','https://motion-primitives.com','motion react components'],
  ['transitions','Transitions.dev','https://transitions.dev','motion transitions react'],
  ['uiverse','Uiverse','https://uiverse.io','components css react'],
  ['uiable','UIAble','https://uiable.com','components shadcn react'],
  ['mapcn','mapcn','https://mapcn.dev','maps components react'],
  ['microkit','MicroKit UI','https://microkit.co','microinteractions components'],
  ['kinetics','Kinetics','https://kinetics.colorion.co','motion css react prompts'],
  ['animejs','Anime.js','https://animejs.com','animation javascript library'],
  ['liquid-glass','Liquid Glass','https://glass.samasante.com','glass react components'],
  ['text-effects','CSS Text Effects','https://text-effects.colorion.co','css text motion'],
  ['circle-loaders','Circle Loaders','https://circleloaders.dominikakissi.com','svg loaders'],
  ['gradient-buttons','Gradient Buttons','https://gradientbuttons.colorion.co','css buttons'],
  ['kitbitz','Kitbitz','https://kitbitz.art','illustrations assets'],
  ['3dicons','3Dicons','https://3dicons.co','icons 3d assets'],
  ['deck-gallery','Deck.gallery','https://deck.gallery','reference presentations design'],
  ['godly','Godly','https://godly.design','reference websites design'],
  ['minimal-gallery','Minimal Gallery','https://minimal.gallery','reference websites minimal'],
  ['component-gallery','Component Gallery','https://component.gallery','reference components design-systems'],
  ['appshot','AppShot Gallery','https://appshot.gallery','reference mobile ui'],
  ['navbar-gallery','Navbar Gallery','https://navbar.gallery','reference navbar'],
  ['footer-design','Footer Design','https://footer.design','reference footer'],
  ['cta-gallery','CTA Gallery','https://cta.gallery','reference cta conversion'],
  ['404s','404s.design','https://404s.design','reference 404'],
  ['refero-styles','Refero Styles','https://styles.refero.design','styles designmd reference'],
  ['designmd','DESIGNmd','https://designmd.ai','designmd styles agents'],
  ['kage','Kage','https://kage.design','reference prompts ui'],
  ['vibeui','VibeUI','https://vibeui.online','prompts layouts patterns'],
  ['vibeprompts','VibePrompt','https://vibeprompts.dev','prompts ui'],
  ['scrolltide','Scrolltide','https://scrolltide.co','prompts scrollytelling 3d'],
  ['backgrounds','Backgrounds Supply','https://backgrounds.supply','backgrounds media assets'],
  ['animos','Animos','https://animos.app','motion video tool'],
  ['openmotion','OpenMotion','https://openmotion.design','motion product-demo tool'],
  ['iconcreator','IconCreator','http://iconcreator.dev','icons generator tool'],
  ['voicestudio','VoiceStudio','http://voicestudio.sh','voice audio tool'],
  ['maildev','MailDev','http://maildev.github.io/maildev','email testing developer-tool'],
  ['agent-memory','Agent Memory','http://agent-memory.dev','agent memory developer-tool'],
  ['vibeindex','VibeIndex','https://vibeindex.dev','directory discovery developer-tools'],
  ['openclaude','OpenClaude','http://openclaude.gitlawb.com','coding-agent cli'],
].map(([id,name,url,tags]) => ({
  id, name, url, adapter: 'reference', enabled: true,
  allowCodeIngest: false, tags: tags.split(' '), license: null,
}));
