const ref=(id,name,url,tags=[],extra={})=>({id,name,url,adapter:'reference',enabled:true,allowCodeIngest:false,tags,license:null,policy:{metadataAllowed:true,codeIngestAllowed:false,mediaIngestAllowed:false,attributionRequired:false,notes:null},...extra});
const deep=(id,name,url,adapter,tags=[],extra={})=>({id,name,url,adapter,enabled:true,allowCodeIngest:false,tags,license:null,policy:{metadataAllowed:true,codeIngestAllowed:false,mediaIngestAllowed:false,attributionRequired:false,notes:null},...extra});
export const DEFAULT_SOURCES=[
  deep('shadcn','shadcn/ui','https://ui.shadcn.com','shadcn',['components','design-system','react','tailwind'],{namespace:'shadcn',installPrefix:'',catalogUrl:'https://ui.shadcn.com/r/index.json'}),
  deep('21st','21st.dev','https://21st.dev','remote-provider',['components','registry','react','ai'],{provider:'21st',remote:true,authEnv:'API_KEY_21ST',mcpUrl:'https://21st.dev/api/mcp',remoteCommand:{executable:'npx',args:['@21st-dev/cli@latest','search','{query}','--json']}}),
  deep('magicui','Magic UI','https://magicui.design','shadcn',['components','animation','react','marketing'],{namespace:'magicui',installPrefix:'@magicui/',sitemapUrl:'https://magicui.design/sitemap.xml',sitemapInclude:['/docs/components/']}),
  ref('aceternity','Aceternity UI','https://ui.aceternity.com/components',['components','animation','react','tailwind']),
  ref('open-props','Open Props','https://open-props.style',['css','tokens','design-system']),
  ref('obsidianui','Obsidian UI','https://www.obsidianui.dev/components',['components','react']),
  ref('rewampui','Rewamp UI','https://www.rewampui.com/components',['components','react']),
  deep('watermelon','Watermelon UI','https://ui.watermelon.sh','shadcn',['components','blocks','shadcn'],{registryTemplate:'https://registry.watermelon.sh/r/{name}.json',sitemapUrl:'https://ui.watermelon.sh/sitemap.xml',sitemapInclude:['/block/','/components/','/dashboard/','/template/']}),
  deep('motion-primitives','Motion Primitives','https://motion-primitives.com','command-provider',['motion','react','components'],{command:{executable:'npx',args:['motion-primitives@latest','add','{item}']},dependencies:['motion','lucide-react','clsx','tailwind-merge'],sitemapUrl:'https://motion-primitives.com/sitemap.xml',sitemapInclude:['/docs/']}),
  ref('transitions','Transitions.dev','https://transitions.dev',['motion','transitions','react']),
  ref('uiverse','Uiverse','https://uiverse.io',['components','css','react']),
  ref('uiable','UIAble','https://uiable.com',['components','shadcn','react']),
  ref('mapcn','mapcn','https://mapcn.dev',['maps','components','react']),
  ref('microkit','MicroKit UI','https://microkit.co',['microinteractions','components']),
  ref('kinetics','Kinetics','https://kinetics.colorion.co',['motion','css','react','prompts']),
  ref('animejs','Anime.js','https://animejs.com',['animation','javascript','library']),
  ref('liquid-glass','Liquid Glass','https://glass.samasante.com',['glass','react','components']),
  ref('text-effects','CSS Text Effects','https://text-effects.colorion.co',['css','text','motion']),
  ref('circle-loaders','Circle Loaders','https://circleloaders.dominikakissi.com',['svg','loaders']),
  ref('gradient-buttons','Gradient Buttons','https://gradientbuttons.colorion.co',['css','buttons']),
  ref('kitbitz','Kitbitz','https://kitbitz.art',['illustrations','assets']),
  ref('3dicons','3Dicons','https://3dicons.co',['icons','3d','assets']),
  deep('deck-gallery','Deck.gallery','https://deck.gallery','deck-gallery',['reference','presentations','design'],{catalog:{decks:'https://deck.gallery/api/catalog/decks.json',products:'https://deck.gallery/api/catalog/products.json'}}),
  ref('godly','Godly','https://godly.design',['reference','websites','design']),
  ref('minimal-gallery','Minimal Gallery','https://minimal.gallery',['reference','websites','minimal']),
  ref('component-gallery','Component Gallery','https://component.gallery',['reference','components','design-systems']),
  ref('appshot','AppShot Gallery','https://appshot.gallery',['reference','mobile','ui']),
  ref('navbar-gallery','Navbar Gallery','https://navbar.gallery',['reference','navbar']),
  ref('footer-design','Footer Design','https://footer.design',['reference','footer']),
  ref('cta-gallery','CTA Gallery','https://cta.gallery',['reference','cta','conversion']),
  ref('404s','404s.design','https://404s.design',['reference','404']),
  deep('refero-styles','Refero Styles','https://styles.refero.design','design',['styles','designmd','reference'],{detailTemplate:'https://styles.refero.design/style/{id}'}),
  deep('designmd','DESIGNmd','https://designmd.ai','design',['designmd','styles','agents']),
  ref('kage','Kage','https://kage.design',['reference','prompts','ui']),
  ref('vibeui','VibeUI','https://vibeui.online',['prompts','layouts','patterns']),
  ref('vibeprompts','VibePrompt','https://vibeprompts.dev',['prompts','ui']),
  ref('scrolltide','Scrolltide','https://scrolltide.co',['prompts','scrollytelling','3d']),
  ref('backgrounds','Backgrounds Supply','https://backgrounds.supply',['backgrounds','media','assets']),
  ref('animos','Animos','https://animos.app',['motion','video','tool']),
  ref('openmotion','OpenMotion','https://openmotion.design',['motion','product-demo','tool']),
  ref('iconcreator','IconCreator','https://iconcreator.dev',['icons','generator','tool']),
  ref('voicestudio','VoiceStudio','https://voicestudio.sh',['voice','audio','tool']),
  ref('maildev','MailDev','https://maildev.github.io/maildev',['email','testing','developer-tool']),
  ref('agent-memory','Agent Memory','https://agent-memory.dev',['agent','memory','developer-tool']),
  deep('vibeindex','VibeIndex','https://vibeindex.dev','vibeindex',['directory','discovery','developer-tools']),
  ref('openclaude','OpenClaude','https://openclaude.gitlawb.com',['coding-agent','cli']),
  ref('base-ui','Base UI','https://base-ui.com',['components','headless','react','accessibility']),
  ref('radix-ui','Radix UI','https://www.radix-ui.com',['components','primitives','react','accessibility']),
  ref('react-aria','React Aria Components','https://react-spectrum.adobe.com/react-aria',['components','react','accessibility','i18n']),
  ref('headless-ui','Headless UI','https://headlessui.com',['components','headless','react','vue']),
  ref('daisyui','daisyUI','https://daisyui.com',['tailwind','components','themes','css']),
  ref('flowbite','Flowbite','https://flowbite.com',['tailwind','components','blocks']),
  ref('preline','Preline UI','https://preline.co',['tailwind','components','html']),
  ref('heroui','HeroUI','https://www.heroui.com',['components','react','application-ui']),
  ref('hyperui','HyperUI','https://www.hyperui.dev',['tailwind','components','blocks']),
  ref('lucide','Lucide','https://lucide.dev',['icons','svg','react'],{kind:'capability'}),
  ref('iconify','Iconify','https://iconify.design',['icons','svg','aggregator'],{kind:'capability'}),
  ref('heroicons','Heroicons','https://heroicons.com',['icons','svg'],{kind:'capability'}),
  ref('tabler-icons','Tabler Icons','https://tabler.io/icons',['icons','svg'],{kind:'capability'}),
  ref('phosphor-icons','Phosphor Icons','https://phosphoricons.com',['icons','svg'],{kind:'capability'}),
  ref('fontsource','Fontsource','https://fontsource.org',['fonts','npm','typography'],{kind:'capability'}),
  ref('react-three-fiber','React Three Fiber','https://r3f.docs.pmnd.rs',['3d','webgl','react'],{kind:'capability'}),
  ref('drei','Drei','https://drei.docs.pmnd.rs',['3d','webgl','react','helpers'],{kind:'capability'}),
  ref('recharts','Recharts','https://recharts.org',['charts','react','visualization'],{kind:'capability'}),
  ref('echarts','Apache ECharts','https://echarts.apache.org',['charts','visualization'],{kind:'capability'}),
  ref('visx','Visx','https://airbnb.io/visx',['charts','react','visualization'],{kind:'capability'}),
  ref('tanstack-table','TanStack Table','https://tanstack.com/table',['table','data-grid','react'],{kind:'capability'}),
];
