import path from 'node:path';
import { VERSION, initWorkspace, rebuildIndex, searchAssets, getAsset, installAsset, auditRegistry, doctor, listSources, addSource, syncSources, sourceProbe, providerStatuses } from './core.mjs';
import { searchAll } from './search.mjs';
import { designSearch, getDesign } from './design.mjs';
import { discoverSources, listDiscovery, approveDiscovery } from './discovery.mjs';
import { runMcp } from './mcp.mjs';
function parse(args){const positional=[],flags={};for(let i=0;i<args.length;i++){const t=args[i];if(!t.startsWith('--')){positional.push(t);continue;}const [raw,inline]=t.slice(2).split('=',2);if(raw.startsWith('no-')){flags[raw.slice(3)]=false;continue;}if(inline!==undefined){flags[raw]=inline;continue;}if(args[i+1]&&!args[i+1].startsWith('--'))flags[raw]=args[++i];else flags[raw]=true;}return{positional,flags};}
const print=v=>process.stdout.write((typeof v==='string'?v:JSON.stringify(v,null,2))+'\n');
const compact=i=>({id:i.id,title:i.title,type:i.type,source:i.source?.id,tags:i.tags,installable:(i.install?.mode||((i.files||[]).length?'cached-files':'none'))!=='none',installMode:i.install?.mode||'none',license:i.license?.id||null});
const help=()=>`WebForge ${VERSION}\nUsage: webforge search <query> [--remote] | provider status [id] | source probe <id> | design search|get | discover [list|approve]`;
export async function main(argv=process.argv.slice(2)){const {positional,flags}=parse(argv),command=positional[0]||'help',root=path.resolve(String(flags.root||process.env.WEBFORGE_ROOT||process.cwd()));if(command==='help'||flags.help){print(help());return;}if(command==='init'){print(await initWorkspace(root));return;}if(command==='bootstrap'){await initWorkspace(root);print(await syncSources(root,{concurrency:Number(flags.concurrency||4)}));return;}if(command==='doctor'){print(await doctor(root));return;}if(command==='index'){print(await rebuildIndex(root));return;}if(command==='search'){await initWorkspace(root);const q=positional.slice(1).join(' ');if(flags.remote)print(await searchAll(root,q,{remote:true,limit:flags.limit||5,type:flags.type,source:flags.source,license:flags.license,installable:Boolean(flags.installable)}));else print(searchAssets(root,q,{type:flags.type,source:flags.source,limit:flags.limit||5,license:flags.license,installable:Boolean(flags.installable),category:flags.category,framework:flags.framework}).map(compact));return;}if(command==='get'){await initWorkspace(root);print(getAsset(root,positional[1])||{error:'not found',id:positional[1]});return;}if(command==='install'){await initWorkspace(root);print(await installAsset(root,positional[1],path.resolve(String(flags.project||process.cwd())),{installDependencies:flags.deps!==false,force:Boolean(flags.force)}));return;}if(command==='audit'){print(await auditRegistry(root));return;}if(command==='mcp'){await runMcp(root);return;}if(command==='provider'&&positional[1]==='status'){print(await providerStatuses(root,positional[2]||null));return;}if(command==='design'){if(positional[1]==='search'){print(designSearch(root,positional.slice(2).join(' '),{limit:flags.limit||5}));return;}if(positional[1]==='get'){print((await getDesign(root,positional[2]))||{error:'not found'});return;}}if(command==='discover'){if(positional[1]==='list'){print(await listDiscovery(root));return;}if(positional[1]==='approve'){print(await approveDiscovery(root,positional[2]));return;}print(await discoverSources(root,{source:flags.source||'vibeindex',items:[]}));return;}if(command==='source'){const sub=positional[1];if(sub==='list'){print(await listSources(root));return;}if(sub==='add'){print(await addSource(root,{url:positional[2],id:flags.id,name:flags.name,adapter:flags.adapter||'auto',manifestUrl:flags.manifest,allowCodeIngest:Boolean(flags.code),license:flags.license||null,tags:String(flags.tags||'').split(',').filter(Boolean)}));return;}if(sub==='sync'){print(await syncSources(root,{id:positional[2],concurrency:Number(flags.concurrency||4)}));return;}if(sub==='probe'){print(await sourceProbe(root,positional[2]));return;}}throw new Error(`unknown command: ${positional.join(' ')}\n${help()}`);}
