import path from 'node:path';
import { VERSION, initWorkspace, rebuildIndex, searchAssets, getAsset, installAsset, auditRegistry, doctor, listSources, addSource, syncSources } from './core.mjs';
import { runMcp } from './mcp.mjs';

function parse(args){const positional=[],flags={};for(let i=0;i<args.length;i++){const t=args[i];if(!t.startsWith('--')){positional.push(t);continue;}const [raw,inline]=t.slice(2).split('=',2);if(raw.startsWith('no-')){flags[raw.slice(3)]=false;continue;}if(inline!==undefined){flags[raw]=inline;continue;}if(args[i+1]&&!args[i+1].startsWith('--'))flags[raw]=args[++i];else flags[raw]=true;}return{positional,flags};}
const print=value=>process.stdout.write((typeof value==='string'?value:JSON.stringify(value,null,2))+'\n');
const compact=item=>({id:item.id,title:item.title,type:item.type,source:item.source?.id,tags:item.tags,dependencies:item.dependencies,installable:Boolean(item.files?.some(f=>f.content||f.url)),license:item.license?.id||null});
const help=()=>`WebForge ${VERSION}\n\nUsage:\n  webforge init [--root DIR]\n  webforge bootstrap [--root DIR] [--concurrency 4]\n  webforge doctor [--root DIR]\n  webforge index [--root DIR]\n  webforge search <query> [--type TYPE] [--source ID] [--limit 5]\n  webforge get <asset-id>\n  webforge install <asset-id> [--project DIR] [--no-deps] [--force]\n  webforge audit\n  webforge source list\n  webforge source add <url> [--id ID] [--adapter auto|reference|shadcn] [--manifest URL] [--code] [--license SPDX]\n  webforge source sync [source-id] [--concurrency 4]\n  webforge mcp [--root DIR]\n`;
export async function main(argv=process.argv.slice(2)){const {positional,flags}=parse(argv),command=positional[0]||'help',root=path.resolve(String(flags.root||process.env.WEBFORGE_ROOT||process.cwd()));if(command==='help'||flags.help){print(help());return;}if(command==='init'){print(await initWorkspace(root));return;}if(command==='bootstrap'){await initWorkspace(root);print(await syncSources(root,{concurrency:Number(flags.concurrency||4)}));return;}if(command==='doctor'){print(await doctor(root));return;}if(command==='index'){print(await rebuildIndex(root));return;}if(command==='search'){await initWorkspace(root);print(searchAssets(root,positional.slice(1).join(' '),{type:flags.type,source:flags.source,limit:flags.limit||5}).map(compact));return;}if(command==='get'){await initWorkspace(root);print(getAsset(root,positional[1])||{error:'not found',id:positional[1]});return;}if(command==='install'){await initWorkspace(root);print(await installAsset(root,positional[1],path.resolve(String(flags.project||process.cwd())),{installDependencies:flags.deps!==false,force:Boolean(flags.force)}));return;}if(command==='audit'){print(await auditRegistry(root));return;}if(command==='mcp'){await runMcp(root);return;}if(command==='source'){const sub=positional[1];if(sub==='list'){print(await listSources(root));return;}if(sub==='add'){print(await addSource(root,{url:positional[2],id:flags.id,name:flags.name,adapter:flags.adapter||'auto',manifestUrl:flags.manifest,allowCodeIngest:Boolean(flags.code),license:flags.license||null,tags:String(flags.tags||'').split(',').filter(Boolean)}));return;}if(sub==='sync'){print(await syncSources(root,{id:positional[2],concurrency:Number(flags.concurrency||4)}));return;}}throw new Error(`unknown command: ${positional.join(' ')}\n\n${help()}`);}
