import { DatabaseSync } from 'node:sqlite';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { DEFAULT_SOURCES } from './catalog.mjs';
import { createProviderContext } from './provider-context.mjs';
import { resolveAdapter, providerStatus as adapterProviderStatus } from './adapters/index.mjs';
import { normalizeShadcnPayload } from './adapters/shadcn.mjs';
import { normalizeDeckCatalog } from './adapters/deck-gallery.mjs';
import { normalizeDesignPayload } from './adapters/design.mjs';
import { installItem, safeDestination } from './install.mjs';
export { DEFAULT_SOURCES, normalizeShadcnPayload, normalizeDeckCatalog, normalizeDesignPayload };
export const normalizeRegistryPayload = normalizeShadcnPayload;
export const VERSION='0.2.0';
const SOURCE_FILE='sources.json', STATE_DIR='.webforge', REGISTRY_DIR=path.join('registry','sources');
const uniq=a=>[...new Set((Array.isArray(a)?a:[]).map(String).filter(Boolean))];
const sourcePath=root=>path.join(root,SOURCE_FILE), registryPath=root=>path.join(root,REGISTRY_DIR), dbPath=root=>path.join(root,STATE_DIR,'index.sqlite');
async function jsonRead(file,fallback){try{return JSON.parse(await readFile(file,'utf8'));}catch(e){if(e?.code==='ENOENT')return fallback;throw e;}}
async function jsonWrite(file,v){await mkdir(path.dirname(file),{recursive:true});await writeFile(file,JSON.stringify(v,null,2)+'\n');}
export function tokenizeSearch(query){const blocked=new Set(['and','or','not','near']);return String(query||'').toLowerCase().match(/[a-z0-9][a-z0-9._-]*/g)?.filter(x=>!blocked.has(x)).join(' ')||'';}
function openDb(root){
  const db=new DatabaseSync(dbPath(root)); db.exec('PRAGMA journal_mode=WAL;');
  const existing=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='assets'").get();
  if(existing){const cols=new Set(db.prepare('PRAGMA table_info(assets)').all().map(x=>x.name));const required=['id','title','description','type','source_id','tags','categories','frameworks','license_id','install_mode','json'];if(required.some(x=>!cols.has(x)))db.exec('DROP TABLE IF EXISTS asset_fts; DROP TABLE IF EXISTS assets;');}
  db.exec(`CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL,type TEXT NOT NULL,source_id TEXT NOT NULL,tags TEXT NOT NULL,categories TEXT NOT NULL DEFAULT '',frameworks TEXT NOT NULL DEFAULT '',license_id TEXT,install_mode TEXT,json TEXT NOT NULL);CREATE VIRTUAL TABLE IF NOT EXISTS asset_fts USING fts5(id UNINDEXED,title,description,tags,categories,frameworks,source,type,tokenize='porter unicode61');`);return db;
}
export async function initWorkspace(root=process.cwd(),options={}){root=path.resolve(root);await mkdir(path.join(root,STATE_DIR),{recursive:true});await mkdir(registryPath(root),{recursive:true});if(!existsSync(sourcePath(root)))await jsonWrite(sourcePath(root),options.seedSources===false?[]:DEFAULT_SOURCES);const db=openDb(root);db.close();return {root,sources:(await listSources(root)).length};}
async function walkJsonl(dir){const out=[];if(!existsSync(dir))return out;for(const e of await readdir(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())out.push(...await walkJsonl(f));else if(e.isFile()&&e.name.endsWith('.jsonl'))out.push(f);}return out;}
async function readRows(root){const rows=[];for(const f of await walkJsonl(registryPath(root))){const t=await readFile(f,'utf8');for(const [i,line] of t.split(/\r?\n/).entries()){if(!line.trim())continue;try{rows.push(JSON.parse(line));}catch(e){rows.push({__parseError:`${f}:${i+1}: ${e.message}`});}}}return rows;}
export async function rebuildIndex(root=process.cwd()){root=path.resolve(root);await initWorkspace(root,{seedSources:false});const rows=await readRows(root),db=openDb(root);db.exec('BEGIN; DELETE FROM asset_fts; DELETE FROM assets;');const a=db.prepare('INSERT OR REPLACE INTO assets(id,title,description,type,source_id,tags,categories,frameworks,license_id,install_mode,json) VALUES(?,?,?,?,?,?,?,?,?,?,?)');const f=db.prepare('INSERT INTO asset_fts(id,title,description,tags,categories,frameworks,source,type) VALUES(?,?,?,?,?,?,?,?)');let indexed=0;try{for(const item of rows){if(!item?.id||item.__parseError)continue;const title=String(item.title||item.name||item.id),description=String(item.description||''),type=String(item.type||'component'),source=String(item.source?.id||'unknown'),tags=uniq(item.tags).join(' '),categories=uniq(item.categories).join(' '),frameworks=uniq(item.frameworks).join(' '),license=item.license?.id||null,install=item.install?.mode||((item.files||[]).length?'cached-files':'none'),json=JSON.stringify(item);a.run(item.id,title,description,type,source,tags,categories,frameworks,license,install,json);f.run(item.id,title,description,tags,categories,frameworks,source,type);indexed++;}db.exec('COMMIT;');}catch(e){db.exec('ROLLBACK;');throw e;}finally{db.close();}return {indexed,files:(await walkJsonl(registryPath(root))).length};}
function ftsQuery(q){return tokenizeSearch(q).split(' ').filter(Boolean).map(x=>`"${x.replaceAll('"','""')}"*`).join(' AND ');}
export function searchAssets(root=process.cwd(),query='',options={}){const db=openDb(path.resolve(root)),limit=Math.max(1,Math.min(Number(options.limit||5),100));try{const filters=[],params=[];const col=(name,val)=>{if(val!==undefined&&val!==null&&val!==''){filters.push(`${name}=?`);params.push(val);}};col('a.type',options.type);col('a.source_id',options.source);col('a.license_id',options.license);if(options.installable){filters.push("COALESCE(a.install_mode,'none') <> 'none'");}if(options.category){filters.push("(' '||a.categories||' ') LIKE ?");params.push(`% ${options.category} %`);}if(options.framework){filters.push("(' '||a.frameworks||' ') LIKE ?");params.push(`% ${options.framework} %`);}const q=ftsQuery(query);let rows;if(q)rows=db.prepare(`SELECT a.json,bm25(asset_fts) score FROM asset_fts JOIN assets a ON a.id=asset_fts.id WHERE asset_fts MATCH ?${filters.length?' AND '+filters.join(' AND '):''} ORDER BY score,a.title LIMIT ?`).all(q,...params,limit);else rows=db.prepare(`SELECT a.json,0 score FROM assets a ${filters.length?'WHERE '+filters.join(' AND '):''} ORDER BY a.title LIMIT ?`).all(...params,limit);return rows.map(r=>({...JSON.parse(r.json),_score:r.score}));}finally{db.close();}}
export function getAsset(root=process.cwd(),id){const db=openDb(path.resolve(root));try{const r=db.prepare('SELECT json FROM assets WHERE id=?').get(String(id));return r?JSON.parse(r.json):null;}finally{db.close();}}
export async function listSources(root=process.cwd()){const v=await jsonRead(sourcePath(path.resolve(root)),[]);if(!Array.isArray(v))throw new Error(`${SOURCE_FILE} must contain a JSON array`);return v;}
export async function addSource(root=process.cwd(),input={}){root=path.resolve(root);await initWorkspace(root,{seedSources:false});if(!input.url)throw new Error('source url is required');const url=new URL(input.url).toString(),id=String(input.id||new URL(url).hostname.replace(/^www\./,'')).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const sources=await listSources(root);if(sources.some(x=>x.id===id))throw new Error(`source already exists: ${id}`);const source={id,name:input.name||id,url,manifestUrl:input.manifestUrl||null,adapter:input.adapter||'auto',enabled:input.enabled!==false,allowCodeIngest:Boolean(input.allowCodeIngest),tags:uniq(input.tags),license:input.license||null,policy:input.policy||{metadataAllowed:true,codeIngestAllowed:Boolean(input.allowCodeIngest),mediaIngestAllowed:false,attributionRequired:false,notes:null},...input};sources.push(source);await jsonWrite(sourcePath(root),sources);return source;}
export async function syncSource(root=process.cwd(),sourceOrId,options={}){root=path.resolve(root);const sources=await listSources(root),source=typeof sourceOrId==='string'?sources.find(x=>x.id===sourceOrId):sourceOrId;if(!source)throw new Error(`source not found: ${sourceOrId}`);if(source.enabled===false)return {id:source.id,skipped:true,reason:'disabled'};const context=createProviderContext(root,options.context||{}),adapter=await resolveAdapter(source,context);const items=await adapter.sync(source,context);await context.writeSnapshot(source.id,items);return {id:source.id,ok:true,adapter:adapter.id,items:items.length,codeIncluded:items.some(x=>x.files?.some(f=>typeof f.content==='string'))};}
async function mapLimit(values,limit,worker){const out=new Array(values.length);let cur=0;async function run(){while(cur<values.length){const i=cur++;try{out[i]=await worker(values[i]);}catch(e){out[i]={id:values[i]?.id,ok:false,code:e.code||'unavailable',error:e.message};}}}await Promise.all(Array.from({length:Math.min(limit,Math.max(1,values.length))},run));return out;}
export async function syncSources(root=process.cwd(),options={}){root=path.resolve(root);const sources=(await listSources(root)).filter(x=>x.enabled!==false&&(!options.id||x.id===options.id));if(options.id&&!sources.length)throw new Error(`source not found: ${options.id}`);const results=await mapLimit(sources,Number(options.concurrency||4),s=>syncSource(root,s,options));const index=await rebuildIndex(root);return {results,index,failed:results.filter(x=>x.ok===false).length};}
export async function sourceProbe(root=process.cwd(),id,options={}){const source=(await listSources(root)).find(x=>x.id===id);if(!source)throw new Error(`source not found: ${id}`);return adapterProviderStatus(source,createProviderContext(root,options.context||{}));}
export async function providerStatuses(root=process.cwd(),id=null,options={}){const sources=(await listSources(root)).filter(x=>!id||x.id===id);return Promise.all(sources.map(s=>adapterProviderStatus(s,createProviderContext(root,options.context||{}))));}
export async function getAssetAny(root=process.cwd(),id,options={}){const local=getAsset(root,id);if(local)return local;const sourceId=String(id||'').split('/')[0],source=(await listSources(root)).find(x=>x.id===sourceId);if(!source)return null;const context=createProviderContext(root,options.context||{}),adapter=await resolveAdapter(source,context);if(typeof adapter.get!=='function')return null;return adapter.get(source,id,context);}
export async function installAsset(root=process.cwd(),id,projectRoot=process.cwd(),options={}){const item=getAsset(root,id),context=createProviderContext(root,options.context||{});if(item)return installItem(item,projectRoot,options,context);const sourceId=String(id||'').split('/')[0],source=(await listSources(root)).find(x=>x.id===sourceId);if(!source)throw new Error(`asset not found: ${id}`);const adapter=await resolveAdapter(source,context);if(typeof adapter.install!=='function')throw new Error(`asset not found or provider is not installable: ${id}`);return adapter.install(source,id,projectRoot,options,context);}
export async function auditRegistry(root=process.cwd()){const rows=await readRows(path.resolve(root)),parseErrors=rows.filter(x=>x?.__parseError).map(x=>x.__parseError),seen=new Map(),duplicates=new Set(),missingLicense=new Set(),unsafeFiles=[];for(const item of rows){if(!item?.id||item.__parseError)continue;if(seen.has(item.id))duplicates.add(item.id);seen.set(item.id,item);if(!item.license?.id)missingLicense.add(item.id);for(const f of item.files||[]){try{safeDestination('/tmp/webforge-audit-root',f.target||f.path);}catch{unsafeFiles.push({id:item.id,path:f.target||f.path});}}}return {totalRows:rows.length-parseErrors.length,uniqueAssets:seen.size,duplicates:[...duplicates].sort(),missingLicense:[...missingLicense].sort(),unsafeFiles,parseErrors};}
export async function doctor(root=process.cwd()){await initWorkspace(root);const sources=await listSources(root),db=openDb(root);let indexedAssets=0;try{indexedAssets=Number(db.prepare('SELECT COUNT(*) n FROM assets').get().n);}finally{db.close();}return {version:VERSION,node:process.version,root:path.resolve(root),sources:sources.length,indexedAssets,sqlite:true};}
