import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
function safe(root,rel){if(!rel||path.isAbsolute(rel))throw new Error(`unsafe file path: ${rel}`);const base=path.resolve(root),dest=path.resolve(base,rel);if(dest!==base&&!dest.startsWith(base+path.sep))throw new Error(`unsafe file path: ${rel}`);return dest;}
async function cached(item,project,options,context){
  const files=[];for(const f of item.files||[]){const rel=f.target||f.path,dest=safe(project,rel);if(!options.force&&existsSync(dest))throw new Error(`refusing to overwrite existing file: ${rel}`);let content=f.content;if(typeof content!=='string'&&f.url)content=(await context.fetchText(new URL(f.url,item.source?.url).toString())).text;if(typeof content!=='string')throw new Error(`asset file has no cached content or URL: ${rel}`);await mkdir(path.dirname(dest),{recursive:true});await writeFile(dest,content);files.push(path.relative(path.resolve(project),dest));}
  const dependencies=[...new Set([...(item.dependencies||[]),...(item.devDependencies||[])])];let dependencyInstall={attempted:false,status:null};
  if(options.installDependencies!==false&&dependencies.length&&existsSync(path.join(path.resolve(project),'package.json'))){dependencyInstall.attempted=true;const r=await context.spawnCommand('npm',['install',...dependencies],{cwd:path.resolve(project)});dependencyInstall.status=r.status;if(r.status!==0)throw new Error(`npm install failed with exit code ${r.status}`);}
  return {mode:'cached-files',filesWritten:files,dependencies,dependencyInstall};
}
function itemName(item){return item.name||String(item.id).split('/').slice(1).join('/');}
export async function installItem(item,projectRoot,options={},context){const mode=item.install?.mode||((item.files||[]).length?'cached-files':'none');if(mode==='cached-files')return cached(item,projectRoot,options,context);if(mode==='none')throw new Error(`asset is not installable: ${item.id}`);if(mode==='shadcn'){const address=item.install.address||itemName(item);const r=await context.spawnCommand('npx',['shadcn@latest','add',address],{cwd:path.resolve(projectRoot)});if(r.status!==0)throw new Error(`shadcn install failed with exit code ${r.status}`);return {mode,address,status:r.status};}if(mode==='command'){const executable=item.install.executable;if(!executable)throw new Error('command provider has no executable');const args=(item.install.args||[]).map(a=>a==='{item}'?itemName(item):a==='{project}'?path.resolve(projectRoot):a);const r=await context.spawnCommand(executable,args,{cwd:path.resolve(projectRoot)});if(r.status!==0)throw new Error(`provider command failed with exit code ${r.status}`);return {mode,executable,args,status:r.status};}if(mode==='remote'){if(context.remoteInstall)return context.remoteInstall(item,projectRoot,options);const e=new Error('remote install provider unavailable');e.code='unavailable';throw e;}throw new Error(`unsupported install mode: ${mode}`);}
export { safe as safeDestination };
