import readline from 'node:readline';
import { VERSION, initWorkspace, searchAssets, getAsset, installAsset, listSources, syncSources, auditRegistry } from './core.mjs';

const LEGACY='2025-11-25', MODERN='2026-07-28';
const meta=()=>({name:'webforge',version:VERSION});
const compact=item=>({id:item.id,title:item.title,type:item.type,source:item.source?.id,tags:item.tags,dependencies:item.dependencies,installable:Boolean(item.files?.some(f=>f.content||f.url)),license:item.license?.id||null});
export const mcpTools=()=>[
  {name:'webforge_search',description:'Search WebForge before generating a replacement.',inputSchema:{type:'object',properties:{query:{type:'string'},type:{type:'string'},source:{type:'string'},limit:{type:'integer',minimum:1,maximum:20}},required:['query']}},
  {name:'webforge_get',description:'Get full metadata and cached files for one selected asset.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id']}},
  {name:'webforge_install',description:'Install one selected asset into a project directory.',inputSchema:{type:'object',properties:{id:{type:'string'},projectRoot:{type:'string'},installDependencies:{type:'boolean'},force:{type:'boolean'}},required:['id','projectRoot']}},
  {name:'webforge_sources',description:'List configured WebForge sources.',inputSchema:{type:'object',properties:{}}},
  {name:'webforge_sync',description:'Refresh one source or all enabled sources and rebuild the index.',inputSchema:{type:'object',properties:{source:{type:'string'},concurrency:{type:'integer',minimum:1,maximum:12}}}},
  {name:'webforge_audit',description:'Audit duplicate IDs, missing license metadata, parse failures, and unsafe paths.',inputSchema:{type:'object',properties:{}}},
];
async function call(root,name,args={}){if(name==='webforge_search')return searchAssets(root,args.query||'',{type:args.type,source:args.source,limit:args.limit||5}).map(compact);if(name==='webforge_get')return getAsset(root,args.id)||{error:'not found',id:args.id};if(name==='webforge_install')return installAsset(root,args.id,args.projectRoot,{installDependencies:args.installDependencies!==false,force:Boolean(args.force)});if(name==='webforge_sources')return listSources(root);if(name==='webforge_sync')return syncSources(root,{id:args.source,concurrency:args.concurrency||4});if(name==='webforge_audit')return auditRegistry(root);throw new Error(`unknown tool: ${name}`);}
function send(message,modern=false){if(modern&&message?.result&&typeof message.result==='object')message.result._meta={...(message.result._meta||{}),'io.modelcontextprotocol/serverInfo':meta()};process.stdout.write(JSON.stringify(message)+'\n');}
export async function runMcp(root=process.cwd()){await initWorkspace(root);let modern=false;const rl=readline.createInterface({input:process.stdin,crlfDelay:Infinity});for await(const line of rl){if(!line.trim())continue;let req;try{req=JSON.parse(line);}catch{continue;}const id=req.id;try{if(req.method==='server/discover'){modern=true;send({jsonrpc:'2.0',id,result:{supportedVersions:[MODERN],capabilities:{tools:{}},instructions:'Search WebForge before generating UI. Retrieve only selected assets. Respect license metadata.'}},true);continue;}if(req.method==='initialize'){modern=false;send({jsonrpc:'2.0',id,result:{protocolVersion:LEGACY,capabilities:{tools:{listChanged:false}},serverInfo:meta(),instructions:'Search WebForge before generating UI. Retrieve only selected assets.'}});continue;}if(req.method?.startsWith('notifications/'))continue;if(req.method==='ping'){send({jsonrpc:'2.0',id,result:{}},modern);continue;}if(req.method==='tools/list'){send({jsonrpc:'2.0',id,result:{tools:mcpTools()}},modern);continue;}if(req.method==='tools/call'){const result=await call(root,req.params?.name,req.params?.arguments||{});send({jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(result)}],structuredContent:result}},modern);continue;}if(id!==undefined)send({jsonrpc:'2.0',id,error:{code:-32601,message:`Method not found: ${req.method}`}},modern);}catch(error){if(id!==undefined)send({jsonrpc:'2.0',id,error:{code:-32000,message:error.message}},modern);}}}
