import readline from 'node:readline';
import { VERSION, initWorkspace, searchAssets, getAssetAny, installAsset, listSources, syncSources, auditRegistry, providerStatuses } from './core.mjs';
import { searchAll } from './search.mjs';
import { designSearch, getDesign } from './design.mjs';
import { discoverSources } from './discovery.mjs';
const LEGACY='2025-11-25',MODERN='2026-07-28',meta=()=>({name:'webforge',version:VERSION});
const compact=i=>({id:i.id,title:i.title,type:i.type,source:i.source?.id,tags:i.tags||[],license:i.license?.id||null,installable:(i.install?.mode||((i.files||[]).length?'cached-files':'none'))!=='none',installMode:i.install?.mode||'none'});
export const mcpTools=()=>[
{name:'webforge_search',description:'Search local WebForge index.',inputSchema:{type:'object',properties:{query:{type:'string'},type:{type:'string'},source:{type:'string'},limit:{type:'integer'}},required:['query']}},
{name:'webforge_get',description:'Get one selected asset.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id']}},
{name:'webforge_install',description:'Install one selected asset.',inputSchema:{type:'object',properties:{id:{type:'string'},projectRoot:{type:'string'},force:{type:'boolean'}},required:['id','projectRoot']}},
{name:'webforge_sources',description:'List sources.',inputSchema:{type:'object',properties:{}}},
{name:'webforge_sync',description:'Sync source(s).',inputSchema:{type:'object',properties:{source:{type:'string'},concurrency:{type:'integer'}}}},
{name:'webforge_audit',description:'Audit registry.',inputSchema:{type:'object',properties:{}}},
{name:'webforge_provider_status',description:'Inspect provider capabilities/status.',inputSchema:{type:'object',properties:{source:{type:'string'}}}},
{name:'webforge_search_remote',description:'Opt-in local plus remote provider search.',inputSchema:{type:'object',properties:{query:{type:'string'},limit:{type:'integer'}},required:['query']}},
{name:'webforge_design_search',description:'Search compact design/style references.',inputSchema:{type:'object',properties:{query:{type:'string'},limit:{type:'integer'}},required:['query']}},
{name:'webforge_design_get',description:'Get one full design reference including DESIGN.md if available.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id']}},
{name:'webforge_discover',description:'Run/add discovery candidates; candidates are never auto-approved.',inputSchema:{type:'object',properties:{source:{type:'string'},items:{type:'array',items:{type:'object'}}}}}
];
async function call(root,name,args={}){if(name==='webforge_search')return searchAssets(root,args.query||'',{type:args.type,source:args.source,limit:args.limit||5}).map(compact);if(name==='webforge_get')return (await getAssetAny(root,args.id))||{error:'not found',id:args.id};if(name==='webforge_install')return installAsset(root,args.id,args.projectRoot,{force:Boolean(args.force)});if(name==='webforge_sources')return listSources(root);if(name==='webforge_sync')return syncSources(root,{id:args.source,concurrency:args.concurrency||4});if(name==='webforge_audit')return auditRegistry(root);if(name==='webforge_provider_status')return providerStatuses(root,args.source||null);if(name==='webforge_search_remote')return searchAll(root,args.query||'',{remote:true,limit:args.limit||5});if(name==='webforge_design_search')return designSearch(root,args.query||'',{limit:args.limit||5});if(name==='webforge_design_get')return (await getDesign(root,args.id))||{error:'not found',id:args.id};if(name==='webforge_discover')return discoverSources(root,{source:args.source||'vibeindex',items:args.items||[]});throw new Error(`unknown tool: ${name}`);}
function send(m){process.stdout.write(JSON.stringify(m)+'\n');}
export async function runMcp(root=process.cwd()){await initWorkspace(root);const rl=readline.createInterface({input:process.stdin,crlfDelay:Infinity});for await(const line of rl){if(!line.trim())continue;let req;try{req=JSON.parse(line);}catch{continue;}const id=req.id;try{if(req.method==='server/discover'){send({jsonrpc:'2.0',id,result:{supportedVersions:[MODERN],capabilities:{tools:{}},instructions:'Search local WebForge first; retrieve only selected assets and use remote providers explicitly.'}});continue;}if(req.method==='initialize'){send({jsonrpc:'2.0',id,result:{protocolVersion:LEGACY,capabilities:{tools:{listChanged:false}},serverInfo:meta(),instructions:'Search local WebForge first; use remote/design get only when needed.'}});continue;}if(req.method?.startsWith('notifications/'))continue;if(req.method==='ping'){send({jsonrpc:'2.0',id,result:{}});continue;}if(req.method==='tools/list'){send({jsonrpc:'2.0',id,result:{tools:mcpTools()}});continue;}if(req.method==='tools/call'){const result=await call(root,req.params?.name,req.params?.arguments||{});send({jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(result)}],structuredContent:result}});continue;}if(id!==undefined)send({jsonrpc:'2.0',id,error:{code:-32601,message:`Method not found: ${req.method}`}});}catch(e){if(id!==undefined)send({jsonrpc:'2.0',id,error:{code:-32000,message:e.message}});}}}
